### ISSUE TITLE
Questions about gym.make()

### ISSUE THREAD

**Issue by ljjTYJR** [ucsdarclab/dVRL#5]
Hello, I want to run the environment on my local computer (windows10,python==3.6);
Here are my steps:
	1. Since the raw code runs on Linux, to switch to windows, I change the _remoteApi_.so to _remoteApi.dll_
	2. From [iuuse#2](https://github.com/ucsdarclab/dVRL/issues/3), In dVRL_simulator/PsmEnv.py:
	

> 1. Opening the *.ttt environments in V-REP and starting the simulation
> 2. Comment out the lines 65-69 and line 177 in dVRL_simulator/PsmEnv.py
> 3. Where lines 65-69 were, set the variable "self.container_ip" to be localhost 
     (127.0.0.1) since you are running it locally
> 4. A new instance of the PSM environments should now link with the your opened *.ttt file!

And I follow the instructions above, here are my steps:
	i) comment out line 177;
	ii) In line 65-69, change "self.container_ip" to be localhost (127.0.0.1)
as follows:
`self.container = client.containers.run(docker_container, detach = True, **kwargs)`

`proc = subprocess.Popen(['docker','inspect','-f', "'{{range .NetworkSettings.Networks}}{{.IPAddress}}``{{end}}'",self.container.id],stdout=subprocess.PIPE,stderr=subprocess.STDOUT)`

`self.container_ip = "127.0.0.1"`
`# self.container_ip = '.'.join(re.findall('\d+', str(proc.stdout.read())))`

Then I create a file to make a gym env as below:
> `import dVRL_simulator`
> `import gym`
> `import numpy as np`
> 
> `env_reach = gym.make("dVRLReach-v0")`

But I get the error:
> D:\ProgramData\Anaconda3\envs\RLBench\python.exe C:/Users/Administrator/Desktop/dVRL/start_point.py
Traceback (most recent call last):
  File "C:/Users/Administrator/Desktop/dVRL/start_point.py", line 5, in <module>
    env_reach = gym.make("dVRLReach-v0")
  File "D:\ProgramData\Anaconda3\envs\RLBench\lib\site-packages\gym\envs\registration.py", line 156, in make
    return registry.make(id, **kwargs)
  File "D:\ProgramData\Anaconda3\envs\RLBench\lib\site-packages\gym\envs\registration.py", line 101, in make
    env = spec.make(**kwargs)
  File "D:\ProgramData\Anaconda3\envs\RLBench\lib\site-packages\gym\envs\registration.py", line 73, in make
    env = cls(**_kwargs)
  File "C:\Users\Administrator\Desktop\dVRL\dVRL_simulator\environments\reach.py", line 15, in __init__
    docker_container = "vrep_ee_reach")
  File "C:\Users\Administrator\Desktop\dVRL\dVRL_simulator\PsmEnv_Position.py", line 78, in __init__
    docker_container =docker_container)
  File "C:\Users\Administrator\Desktop\dVRL\dVRL_simulator\PsmEnv.py", line 51, in __init__
    environment = {"DISPLAY":os.environ['DISPLAY'], "QT_X11_NO_MITSHM":1}
  File "D:\ProgramData\Anaconda3\envs\RLBench\lib\os.py", line 669, in __getitem__
    raise KeyError(key) from None
KeyError: 'DISPLAY'
Exception ignored in: <bound method PSMEnv.__del__ of <dVRL_simulator.environments.reach.PSMReachEnv object at 0x000001E00B4A25C0>>
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\dVRL\dVRL_simulator\PsmEnv.py", line 127, in __del__
    self.close()
  File "C:\Users\Administrator\Desktop\dVRL\dVRL_simulator\PsmEnv.py", line 176, in close
    vrep.simxFinish(self.clientID)
AttributeError: 'PSMReachEnv' object has no attribute 'clientID'
Process finished with exit code 1

It seems that the error exists because it doesn't connect to vrep, could you give some advice about how to fix this? thanks

**Comment by ljjTYJR** [comment]
Or I want to run on my local computer first, I think I should modify the file _PsmEnv.py_  and connect to local vrep？

**Comment by bango123** [comment]
I believe this is because line 78 from the PSMEnv.py file never ran which defines the self.clientID. Is there a way you can check that this line runs?

**Comment by ljjTYJR** [comment]
I comment out all about docker parameters; 
Then I set the local IP="127.0.0.1", now I use gym.make() I can connect to vrep;
